enyo.depends(
    "$lib/layout",
    "$lib/onyx",
    "App.css",
    "App.js",
    "NoAccelerateArranger.js",
    "Mainline.js",
    "NewsItem.js",
    "TweetItem.js",
    "Toc.js",
    "TocItem.js",
    "libs/Connector.js"
);
